-- Migration: add shipping settings to stores table
ALTER TABLE stores ADD COLUMN IF NOT EXISTS free_shipping_threshold INTEGER NOT NULL DEFAULT 400;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS casa_fee INTEGER NOT NULL DEFAULT 20;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS rabat_fee INTEGER NOT NULL DEFAULT 25;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS other_cities_fee INTEGER NOT NULL DEFAULT 30;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS delivery_timeframe TEXT NOT NULL DEFAULT '24h à 48h';
